config/routes.rb
Rails.application.routes.draw do
  root 'people#home'
  resources :people
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    if @person.update(people_params)
      redirect_to people_path
    else
      render :edit
    end
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(people_params)
    if @person.save
      redirect_to people_path
    else
      render :new
    end
  end

  def destroy
    Person.find(params[:id]).destroy
    redirect_to people_path
  end

  private

  def people_params
    params.require(:person).permit(:first_name, :last_name, :age, :eye_color, :human)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/_navbar.html.erb
<h1><%= button_to 'People', people_path, :method => "get" %></h1>
<h1><%= button_to 'About', root_path, :method => "get" %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>People</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/edit.html.erb
<h2>Edit Entry</h2>
<%= render 'layouts/navbar' %>
<%= yield %>
<hr>

<div>
  <%= form_for @person do |f| %>

    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
    <br>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
    <br>
    <%= f.label :eye_color %>
    <%= f.text_field :eye_color %>
    <br>
    <%= f.label :age %>
    <%= f.text_field :age %>
    <br>
    <%= f.check_box :human %>
    <%= f.label :human %>
    <br>
    <div>
      <%= f.submit %>
    </div>

  <% end %>
</div>
<br>
<hr>
<div>
  <h4><%= button_to "Back", people_path, :method => "get" %></h4>
</div>

app/views/people/home.html.erb
<h1>Welcome to the People List!</h1>
<br>
<br>
<%= render 'layouts/navbar' %>
<%= yield %>

app/views/people/index.html.erb
<h1>People</h1>
<%= render 'layouts/navbar' %>
<%= yield %>

<div>
  <h3><%= button_to 'Add New Person', new_person_path, :method => "get" %></h3>
</div>

<div>
    <% @people.each do |person| %>
    <%= person.first_name %>  <br>  <%= person.last_name %></span>
    <%= link_to 'View', person_path(person) %>
    <%= link_to 'Edit', edit_person_path(person) %>
    <%= link_to 'Delete', person, method: :delete %>

  <% end %>
</div>

app/views/people/new.html.erb
<h2>New Person</h2>
<%= render 'layouts/navbar' %>
<%= yield %>
<hr>
<div>
  <%= form_for @person do |f| %>

    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
    <br>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
    <br>
    <%= f.label :age %>
    <%= f.text_field :age %>
    <br>
    <%= f.label :eye_color %>
    <%= f.text_field :eye_color %>
    <br>
    <%= f.check_box :human %>
    <%= f.label :human %>
    <br>
    <div>
      <%= f.submit %>
    </div>

  <% end %>
</div>

<%= button_to "Back", people_path, :method => "get" %>

app/views/people/show.html.erb
<%= render 'layouts/navbar' %>
<%= yield %>
<hr>
<div><h5>Name:</h5>
  <h4><%= @person.first_name + " " + @person.last_name %></h4>
  <h5>Age:</h5><h4><%= @person.age %></h4>
  <h5>Eye Color: </h5><h4><%= @person.eye_color %></h4>
  <h5>Are they human?</h5><h4><%= @person.human %></h4>
</div>
<hr>
<div>
<%= button_to "Back", people_path, :method => "get" %>
</div>